<Project>
  <ItemGroup>
    <PackageVersion Include="Avalonia" Version="11.2.0-rc1" />
    <PackageVersion Include="Avalonia.Controls.ColorPicker" Version="11.2.0-rc1" />
    <PackageVersion Include="Avalonia.Controls.DataGrid" Version="11.2.0-rc1" />
    <!--<PackageVersion Include="Avalonia.Controls.ItemsRepeater" Version="11.2.0-rc1" />-->
    <PackageVersion Include="Avalonia.Desktop" Version="11.2.0-rc1" />
    <PackageVersion Include="Avalonia.Diagnostics" Version="11.2.0-rc1" />
    <PackageVersion Include="Avalonia.Headless.NUnit" Version="11.2.0-rc1" />
    <PackageVersion Include="Blazored.FluentValidation" Version="2.1.0" />
    <PackageVersion Include="Avalonia.Fonts.Inter" Version="11.2.0-rc1" />
    <PackageVersion Include="Avalonia.Themes.Fluent" Version="11.2.0-rc1" />
    <PackageVersion Include="CommandLineParser" Version="2.9.1" />
    <PackageVersion Include="CommunityToolkit.Maui" Version="7.0.1" />
    <PackageVersion Include="coverlet.collector" Version="6.0.0" />
    <PackageVersion Include="DotNet.ReproducibleBuilds" Version="1.1.1" />
    <PackageVersion Include="FluentAssertions" Version="6.12.0" />
    <PackageVersion Include="Microsoft.AspNetCore.Components" Version="8.0.1" />
    <PackageVersion Include="Microsoft.AspNetCore.Components.WebView.Maui" Version="8.0.6" />
    <PackageVersion Include="Microsoft.Build.Locator" Version="1.7.1" />
    <PackageVersion Include="Microsoft.CodeAnalysis.CSharp.Workspaces" Version="4.8.0" />
    <PackageVersion Include="Microsoft.CodeAnalysis.Workspaces.MSBuild" Version="4.8.0" />
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection" Version="8.0.0" />
    <PackageVersion Include="Microsoft.Extensions.Logging" Version="8.0.0" />
    <PackageVersion Include="Microsoft.Extensions.Http" Version="8.0.0" />
    <PackageVersion Include="Microsoft.Extensions.Logging.Debug" Version="8.0.0" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="17.9.0" />
    <PackageVersion Include="Microsoft.SourceLink.GitHub" Version="8.0.0" />
    <PackageVersion Include="Nerdbank.GitVersioning" Version="3.6.133" />
    <PackageVersion Include="nunit" Version="4.0.1" />
    <PackageVersion Include="NUnit3TestAdapter" Version="4.5.0" />
    <PackageVersion Include="sqlite-net-pcl" Version="1.8.116" />
    <PackageVersion Include="SQLitePCLRaw.core" Version="2.1.8" />
    <PackageVersion Include="SQLitePCLRaw.bundle_green" Version="2.1.8" />
    <PackageVersion Include="SQLitePCLRaw.provider.dynamic_cdecl" Version="2.1.8" />
    <PackageVersion Include="UraniumUI.Icons.FontAwesome" Version="2.7.4" />
  </ItemGroup>
</Project>