<Project Sdk="Microsoft.NET.Sdk.Razor">

	<PropertyGroup>
		<TargetFrameworks>net10.0</TargetFrameworks>
		<!--<TargetFrameworks Condition="$([MSBuild]::IsOSPlatform('windows'))">$(TargetFrameworks);net8.0-windows10.0.19041.0</TargetFrameworks>-->
		<OutputType>WinExe</OutputType>
		<RootNamespace>ControlGallery</RootNamespace>
		<ImplicitUsings>enable</ImplicitUsings>

		<!--<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'ios'">14.2</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'maccatalyst'">14.0</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'">23.0</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.17763.0</SupportedOSPlatformVersion>
		<TargetPlatformMinVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.17763.0</TargetPlatformMinVersion>-->

		<AndroidManifest>Platforms/Android/AndroidManifest.xml</AndroidManifest>
	</PropertyGroup>

	<ItemGroup>
		<AvaloniaResource Include="Resources\Images\**"/>
	</ItemGroup>
	
	<ItemGroup>
		<PackageReference Include="Avalonia" />
		<PackageReference Include="Avalonia.Desktop" />
		<PackageReference Include="Avalonia.Themes.Fluent" />
		<PackageReference Include="Avalonia.Fonts.Inter" />
		<!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
		<PackageReference Condition="'$(Configuration)' == 'Debug'" Include="Avalonia.Diagnostics" />
		<PackageReference Include="Microsoft.Extensions.Logging" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\..\src\BlazorBindings.AvaloniaBindings\BlazorBindings.AvaloniaBindings.csproj" />
	</ItemGroup>


	<ItemGroup>
	  <Compile Update="App.axaml.cs">
	    <DependentUpon>%(Filename)</DependentUpon>
	  </Compile>
	</ItemGroup>

</Project>