// <auto-generated>
//     This code was generated by a BlazorBindings.Avalonia component generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>



#pragma warning disable CA2252

namespace BlazorBindings.AvaloniaBindings.Elements
{
    /// <summary>
    /// Represents a button that allows a user to select a single option from a group of options.
    /// </summary>
    public partial class RadioButton : BlazorBindings.AvaloniaBindings.Elements.Primitives.ToggleButton
    {
        static RadioButton()
        {
            RegisterAdditionalHandlers();
        }

        /// <summary>
        /// Gets or sets the name that specifies which RadioButton controls are mutually exclusive.
        /// </summary>
        [Parameter] public string GroupName { get; set; }

        public new AC.RadioButton NativeControl => (AC.RadioButton)((AvaloniaObject)this).NativeControl;

        protected override AC.RadioButton CreateNativeElement() => new();

        protected override void HandleParameter(string name, object value)
        {
            switch (name)
            {
                case nameof(GroupName):
                    if (!Equals(GroupName, value))
                    {
                        GroupName = (string)value;
                        NativeControl.GroupName = GroupName;
                    }
                    break;

                default:
                    base.HandleParameter(name, value);
                    break;
            }
        }

        static partial void RegisterAdditionalHandlers();
    }
}
