<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net10.0</TargetFrameworks>
		<Title>Avalonia Blazor Bindings Core Runtime</Title>
		<Description>Common logic for using Blazor to target native renderers. For Avalonia app projects use the BlazorBindings.AvaloniaBindings package.</Description>
		<PackageTags>blazor;blazorbindings</PackageTags>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Components" />
		
		<PackageReference Include="DotNet.ReproducibleBuilds">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>
</Project>
